### ISSUE TITLE
переработать модели Образования в соответствиями с Требованиями к продукту

### ISSUE THREAD

**Issue by Ilyaradaev** [py-psychological-help/---#132]
Паспорт;
Диплом о высшем образовании (Высшее психологическое образование — специалитет или магистратура);
Свидетельство о профессиональной переподготовке (при наличии);
Справка из профильного учебного заведения (для студентов 4-го курса);
Сертификат о повышении квалификации (при наличии)”.

**Comment by sergey-xx** [comment]
пока не менял модели и названия моделей/функций.
сделаю при рефакторинге
