### ISSUE TITLE
Авторизация. Не нажимается кнопка "Войти" при вводе верного пароля профиля психолога. Появилась ошибка "Не соответствует требованиям к полю"

### ISSUE THREAD

**Issue by landsknecht0748** [py-psychological-help/---#135]
Предусловие:

Есть созданный аккаунт например почта - gue@yandex.ru пароль - Qweasd!123

Шаги:

Нажать на кнопку "Психологам" в шапке сайта

Нажать на кнопку "Войти" в шапке сайта

Ввести данные созданного аккаунта в поля почта - gue@yandex.ru и пароль - Qweasd!123

ОР. Авторизация осуществлена. Открыта страница "Чаты" личного кабинета психолога
ФР. Авторизация не осуществлена. Осталась открыта страница авторизации
Приоритет - Высокий
![2024-01-28_14-09-24](https://github.com/py-psychological-help/---/assets/145380032/0eb53a9a-1945-4712-8aa1-c07c6160285d)

**Comment by nuncame** [comment]
![image](https://github.com/py-psychological-help/---/assets/118114048/6f6aede0-ddc6-43c6-8b6e-aeb204300455)

**Comment by landsknecht0748** [comment]
Баг не исправлен. Система не принимает пароль который был принят при регистрации
![2024-01-30_19-05-45](https://github.com/py-psychological-help/---/assets/145380032/bbd8c0d2-4857-4acb-8f3f-8f20edf748ea)

**Comment by landsknecht0748** [comment]
Баг не исправлен. Система не принимает ввод пароля который был принят при регистрации
![2024-01-30_19-25-37](https://github.com/py-psychological-help/---/assets/145380032/5571e808-e607-471c-a19d-3d52be2576f5)
