### ISSUE TITLE
Цвет Заголовка "данные специалиста" "Профиль" в лк  #000000

### ISSUE THREAD

**Issue by landsknecht0748** [py-psychological-help/---#190]
Психолог авторизован

Шаги исполнения:

Открыть на сайт https://dpogovorim.ru/#headerSection

Перейти в личный кабинет, нажав на кнопку "Личный кабинет психолога" в футере

Открыть DevTools

Зажать Ctrl + Shift + C

Навестись на Заголовок "Данные специалиста"

ОР. Цвет иконки в виде человека у кнопки Профиль - #343434
ФР. Цвет иконки в виде человека у кнопки Профиль - #000000
![2024-02-10_16-21-29](https://github.com/py-psychological-help/---/assets/145380032/ad2464a6-a33d-4fc7-9136-1440115b5aa0)
![2024-02-10_16-30-26](https://github.com/py-psychological-help/---/assets/145380032/5ac0dfa1-07f3-4573-be3c-d7c2222a491a)

**Comment by yuli-ageeva** [comment]
@landsknecht0748 неправильно, это не текст и у него не может быть цвета, это иконка из кита (она копируется оттуда)
<img width="1064" alt="image" src="https://github.com/py-psychological-help/---/assets/118059853/7f3d0ae2-1329-419e-8a2c-3f1f97f0bde9">

то что на примере тут не цвет иконки, а цвет текста " данные специалиста"

**Comment by yuli-ageeva** [comment]
цвет текста не тот, согласна

**Comment by yuli-ageeva** [comment]
устранено
